# Generated by Django 5.1.7 on 2025-05-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_medicalstaff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('medical', 'Équipement Médical'), ('surgical', 'Équipement Chirurgical'), ('diagnostic', 'Équipement de Diagnostic'), ('pharmacy', 'Pharmacie'), ('other', 'Autre')], default='medical', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_restocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='minimum_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
