# Generated by Django 5.1.7 on 2025-05-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_equipment_category_equipment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_restocked',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='minimum_quantity',
        ),
        migrations.DeleteModel(
            name='InventoryAlert',
        ),
    ]
