# Generated by Django 5.1.7 on 2025-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_equipment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='role',
            field=models.CharField(choices=[('doctor', 'Médecin'), ('nurse', 'Infirmier(ère)'), ('paramedic', 'Ambulancier(ère)'), ('specialist', 'Spécialiste'), ('intern', 'Interne'), ('other', 'Autre')], max_length=50),
        ),
    ]
